name: Hello World

on:
  schedule:
    - cron: '10 * * * *'   # À la minute 10 de chaque heure (UTC)
  workflow_dispatch:         # Permet de le lancer manuellement (utile pour tester)

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "Hello, world!"

